[workspace]
members = [
    "currency",
    "market",
    "market-data",
    "market-hub",
    "market-log",
    "order-book",
    "stream",
    "stream-ws",
    "stream-poloniex",
    "stream-zmq",
    "util",
]
