[package]
name = "cb-currency"
description = "crypto currency utilities"
version = "0.0.2"
license = "Apache-2.0"
authors = ["Lukasz Kurowski <crackcomm@gmail.com>"]

[dependencies]
serde        = "1.*.*"
bincode      = "0.9.*"
serde_derive = "1.*.*"
error-chain  = "0.11.*"
