[package]
name = "cb-market"
description = "crypto-bank market module"
version = "0.0.1"
license = "Apache-2.0"
authors = ["Lukasz Kurowski <crackcomm@gmail.com>"]

[dependencies]
// cb-util = { path = "../util", version = "*" }
// cb-currency = { path = "../currency", version = "*" }
